## Numpy Basics 
Learn About Numpy

In [1]:
import numpy as np

In [2]:
# creating Array From List

arr_1d = np.array([1,2,3,4,5])
print("1D Array : ",arr_1d,"\n")

arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print("2D Array : ",arr_2d)

1D Array :  [1 2 3 4 5] 

2D Array :  [[1 2 3 4 5]
 [6 7 8 9 0]]


## List Vs Numpy


In [3]:
py_list = [1,2,3,4,5]
print("Multiplication Of List : ", py_list*2)

numpy_arry = np.array([1,2,3,4,5])
print("Multiplication Of Numpy Array : ", numpy_arry*2)

Multiplication Of List :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Multiplication Of Numpy Array :  [ 2  4  6  8 10]


In [4]:
import time

start_time = time.time()
list_py = [i*2 for i in range (1000000)]
print("Creating  Python List Time : ", time.time() - start_time)

start_time = time.time()
array_numpy = np.arange(1000000) * 2
print("Creating  Python Numpy Array Time : ", time.time() - start_time)

Creating  Python List Time :  1.0029993057250977
Creating  Python Numpy Array Time :  0.15096068382263184


In [5]:
zero_arr = np.zeros((3,5))
print(zero_arr)

one_arr = np.ones((3,4))
print(one_arr)

full_arr = np.full((2,3), 7)
print(full_arr)

random_arr = np.random.random((2,3))
print(random_arr)

sequence_arr = np.arange(1,10,2)
print(sequence_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]]


[[4.06504794e-05 2.68004782e-01 1.04414169e-01]
 [1.34492210e-01 5.94610719e-01 1.52115994e-01]]
[1 3 5 7 9]


## Vector, Matrix, Tensor


In [6]:
vector = np.array([1,2,3,4,5])
print("Vector : ", vector)

matrix = np.array([[1,2,3,4],[5,6,7,8]])
print("Matrix : ", matrix)

tensor = np.array([[[1,2,3],[0,9,8]],[[4,5,6],[8,8,0]]])
print("Tensor : ", tensor)

Vector :  [1 2 3 4 5]
Matrix :  [[1 2 3 4]
 [5 6 7 8]]
Tensor :  [[[1 2 3]
  [0 9 8]]

 [[4 5 6]
  [8 8 0]]]


## Array Properties

In [7]:
new_arr = np.array([[1,2,3,4],[5,6,7,8]])
print("How many row and column (row,column) : ",np.shape(new_arr))
print("How many row and column (row,column) : ",new_arr.shape)

print("Total Element in Array : ",np.size(new_arr))
print("Total Element in Array : ",new_arr.size)

print("Now Many Dimantion Of Array : ",np.ndim(new_arr))
print("Now Many Dimantion Of Array : ",new_arr.ndim)

print("DataType type of array : ", new_arr.dtype)

How many row and column (row,column) :  (2, 4)
How many row and column (row,column) :  (2, 4)
Total Element in Array :  8
Total Element in Array :  8
Now Many Dimantion Of Array :  2
Now Many Dimantion Of Array :  2
DataType type of array :  int64


## Array Reshaping

In [8]:
new_arr = np.array([[1,2,3,4,0,1],[5,6,7,8,9,0]])
print(new_arr.reshape(3,4))


arr_n = np.arange(12)
print(arr_n.reshape(3,4))

flattend_arr = new_arr.flatten()
print("N dimension Array Convert into single array : ", flattend_arr)
# Flatten make a copy of original array, mean if we change fltten array then no changes in original array 
flattend_arr[0]=10
print("After Change in flatten array no changes in origional array : ",new_arr)

raveld_Arr = new_arr.ravel()
print(raveld_Arr)

# reval return the original array, it mean if we change any element in ravel array then reval change the original array 
raveld_Arr[0]=99
print("After Change in ravel array it change the original array : ",new_arr)

[[1 2 3 4]
 [0 1 5 6]
 [7 8 9 0]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
N dimension Array Convert into single array :  [1 2 3 4 0 1 5 6 7 8 9 0]
After Change in flatten array no changes in origional array :  [[1 2 3 4 0 1]
 [5 6 7 8 9 0]]
[1 2 3 4 0 1 5 6 7 8 9 0]
After Change in ravel array it change the original array :  [[99  2  3  4  0  1]
 [ 5  6  7  8  9  0]]


In [9]:
arr_n = np.arange(12)
print("Original Array : ", arr_n)

reshaped_Arr = arr_n.reshape(3,4)
print("\nReshape : ", reshaped_Arr)

# Transpose  , it mean if (row,column) then row convert into column and column convert into row e.g. Arr = (3,4), Trand_Arr = (4,3)
transpose_arr = reshaped_Arr.T
print("\nTranspose Array : ",transpose_arr)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshape :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transpose Array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
