## Numpy Array Operation

In [2]:
import numpy as np

In [3]:
my_Arr = np.arange(10)

print("Basics Slicing : ", my_Arr[2:7])
print("Basics Slicing  With Step : ", my_Arr[0:7:2])
print("Basics Slicing  With Negative Indexing : ", my_Arr[-1])

Basics Slicing :  [2 3 4 5 6]
Basics Slicing  With Step :  [0 2 4 6]
Basics Slicing  With Negative Indexing :  9


In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element : ", arr_2d[2,2])
print("Entire Row : ", arr_2d[1])
print("Entire Column : ", arr_2d[:,1])

Specific Element :  9
Entire Row :  [4 5 6]
Entire Column :  [2 5 8]


# Sorting

In [5]:
unsorted_Array = np.array([4,6,8,2,5,1,9,0,3,7])
print("Sorted Array : ", np.sort(unsorted_Array))


unsorted_2d = np.array([[3,1],[4,8],[9,0]])
print("Sorted 2D array by Column : ", np.sort(unsorted_2d, axis=0))
print("Sorted 2D array by Row : ", np.sort(unsorted_2d, axis=1))

Sorted Array :  [0 1 2 3 4 5 6 7 8 9]
Sorted 2D array by Column :  [[3 0]
 [4 1]
 [9 8]]
Sorted 2D array by Row :  [[1 3]
 [4 8]
 [0 9]]


## Filtering

In [6]:
numbers = np.arange(1,11)
print(numbers)

#  this is Called Filtering With Mask
# this called MASK
even_number = numbers %2 == 0
# even_number Return [ture false true false] like this which condithin satisfied "numbers %2 == 0" it return true otherwise false 
# when we perform "numbers[even_number]"  then which value is true it return 
print("Even Number : ",numbers[even_number])

print("Even Number Using One Line : ", numbers[numbers %2 == 0])

[ 1  2  3  4  5  6  7  8  9 10]
Even Number :  [ 2  4  6  8 10]
Even Number Using One Line :  [ 2  4  6  8 10]


## Fancy Indexing VS np.Where()

In [7]:
indexing_value = [0,3,5,7]
print("Print Element Using Fancy Indexing Fancy Indexing : ", numbers[indexing_value])

# Using np.where()

using_where = np.where(numbers %3 == 0)
print("Using np.where()  it Return The Indexing Value of Given Array : ", using_where)
print("Using np.where() Result : ", numbers[using_where])
print("We can perform Direct In One lIne Of Code  : ",numbers[np.where(numbers>5)])

Print Element Using Fancy Indexing Fancy Indexing :  [1 4 6 8]
Using np.where()  it Return The Indexing Value of Given Array :  (array([2, 5, 8]),)
Using np.where() Result :  [3 6 9]
We can perform Direct In One lIne Of Code  :  [ 6  7  8  9 10]


In [8]:
# If the condition is True, use value from x, else use value from y.
# np.where(condition, x, y)
# it devide array into two part x, y,   x mean which is satisfied the condition (numbers>5), y mean which is not satisfied the condition 
# then we give second parameter "numbers*5" (it mean where true then numbers multiply by 5) 
# third parameter "numbers" (where false return numbers)

# numbers vale array me jo element "numbers>5" conditon ko satisfied krte h unme "numbers*5" kr do jo satisfied nhi krte h unko jo "numbers" ki value h original return kr do 
condition_arr = np.where(numbers>5, numbers*5,  numbers)
print(condition_arr)

[ 1  2  3  4  5 30 35 40 45 50]


## Adding And Remove Element From np.array()

In [9]:
array_np_1 = np.array([1,2,3])
array_np_2 = np.array([4,5,6])

combine_Array = np.concatenate((array_np_1, array_np_2))
print(combine_Array)

[1 2 3 4 5 6]


#### checking the shapr of array

In [10]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([1,2,3,4,5])

print("Compatibale or not : ", array_1.shape == array_2.shape)

Compatibale or not :  False


#### Adding Row Or Column

In [11]:
arr = np.array([[1,2],[3,4]])
arr_2 = np.array([5,6])

add_in_row = np.vstack((arr, arr_2))
print("add a new row :", add_in_row)

arr_3 = np.array([[5],[6]])
add_in_coumn = np.hstack((arr, arr_3))
print("add a new column : ", add_in_coumn)

add a new row : [[1 2]
 [3 4]
 [5 6]]
add a new column :  [[1 2 5]
 [3 4 6]]


##### Delete From Array

In [ ]:
original_arr = np.array([1,2,3,4,5,6,7])
# syntax : np.delete(array, index)
deleted_array = np.delete(original_arr, 2)
print(deleted_array)

[1 2 4 5 6 7]


In [18]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
# Delete elements from index 1 to 5 (i.e., 20 to 50)
new_arr = np.delete(arr, np.s_[1:5])

print(new_arr)

[10 60 70]


In [21]:
arr_2d = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print("arr_2d ", arr_2d)
new_arr_delete_from_row = np.delete(arr_2d, 1, axis=0)  # Delete row at index 1

print("\nnew_arr_delete_from_row",new_arr_delete_from_row)

delete_from_column = np.delete(arr_2d, 0, axis=1)  # Delete column at index 0

print("\n delete_from_column",delete_from_column)


arr_2d  [[1 2 3]
 [4 5 6]
 [7 8 9]]

new_arr_delete_from_row [[1 2 3]
 [7 8 9]]

 delete_from_column [[2 3]
 [5 6]
 [8 9]]
